services:
    shapecode_hidden_entity_type.form_type.object:
        class: Shapecode\Bundle\HiddenEntityTypeBundle\Form\Type\HiddenObjectType
        arguments: ["@doctrine"]
        tags:
            - { name: form.type }
